sudo: required

services:
  - docker

before_install:
  - docker build -t indrajithvgp/react-nginx -f Dockerfile .

# script:
#   - docker run -e CI=true indrajithvgp/react-nginx npm run test


deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-beanstalk"
  name: "Dockerbeanstalk-env"
  bucket_name: "elasticbeanstalk-us-east-2-791077991850"
  bucket_path: "docker-beanstalk"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY