sudo: required

services:
  - docker

before_install:
  - docker build -t indrajithvgp/react-nginx -f Dockerfile.dev .

script:
  - docker run -e CI=true indrajithvgp/react-nginx npm run test

languages: generic

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"